### ISSUE TITLE
Messages d'erreur

### ISSUE THREAD

**Issue by ThomasTel** [colombbus/tangara-client#45] opened 2015-07-03 14:30 UTC
-« dir.ajouterCommande("droite", bob.avancer(10)) »
retourne « {0} n'est pas une commande valide ».
-« bob = new Robot(); bob.taille » ne retourne pas d'erreur.

**Comment by LiaOkami** [comment] 2015-08-27 15:21
What is dir in the first command ?
For the second command, this is correct so it doesn't have to return an error.

**Comment by ThomasTel** [comment] 2015-08-27 16:15
....What is dir in the first command ?
A CommandesClavier.

....For the second command, this is correct so it doesn't have to return an error.
It is correct in Javascript but I don't think it is in the philosophy of Declick to allow users to access or create undefined attributes.

**Comment by LiaOkami** [comment] 2015-11-10 11:29
First issue moved to declick-client.
https://github.com/colombbus/declick-client/issues/6

Second issue is a duplicate of this one
https://github.com/colombbus/declick-client/issues/2

**Closed as completed by LiaOkami** 2015-11-10 11:29 UTC
